# Generated by scripts/homebrew-formula.sh in github.com/safegrd/cli for v0.0.6.
# Do not edit by hand: the next release overwrites it.
class Safegrd < Formula
  desc "Encrypted, immutable backups with proof that they restore"
  homepage "https://safegrd.dev"
  version "0.0.6"
  license "BUSL-1.1"

  on_macos do
    on_arm do
      url "https://github.com/safegrd/cli/releases/download/v0.0.6/safegrd_0.0.6_darwin_arm64.tar.gz"
      sha256 "f68828e6bd93d95b0b9c02f70101b483edf873263eb4f40061f8bddd8fd2f389"
    end
    on_intel do
      url "https://github.com/safegrd/cli/releases/download/v0.0.6/safegrd_0.0.6_darwin_amd64.tar.gz"
      sha256 "c056149b69c3b2ad4663aeef2d1940a17d3ea0f33910b27c16264e3f5ef217be"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/safegrd/cli/releases/download/v0.0.6/safegrd_0.0.6_linux_arm64.tar.gz"
      sha256 "b59c4666d96ed26144cad1b5af8b59db76f5dcf44f634b968f43fc34cebe6148"
    end
    on_intel do
      url "https://github.com/safegrd/cli/releases/download/v0.0.6/safegrd_0.0.6_linux_amd64.tar.gz"
      sha256 "f8ea7094d0fd90440f3f8d8814035b5ad81251692000acdf1931bb2770247d47"
    end
  end

  def install
    bin.install "safegrd"
    generate_completions_from_executable(bin/"safegrd", "completion")
  end

  def caveats
    <<~EOS
      Connect this machine to SafeGrd:
        safegrd login     # prints a URL; open it in a browser on any device
        safegrd enroll
      Or set up a standalone host that contacts no server:
        safegrd init
    EOS
  end

  test do
    assert_match "version #{version}", shell_output("#{bin}/safegrd version")
  end
end
