# Generated by scripts/homebrew-formula.sh in github.com/safegrd/cli for v0.0.17.
# Do not edit by hand: the next release overwrites it.
class Safegrd < Formula
  desc "Encrypted, immutable backups with proof that they restore"
  homepage "https://safegrd.dev"
  version "0.0.17"
  license "BUSL-1.1"

  on_macos do
    on_arm do
      url "https://github.com/safegrd/cli/releases/download/v0.0.17/safegrd_0.0.17_darwin_arm64.tar.gz"
      sha256 "92c165babfbfd5ee688b111a3f3dd5b4caf7a924c70b3b814a450bc7b9a2176d"
    end
    on_intel do
      url "https://github.com/safegrd/cli/releases/download/v0.0.17/safegrd_0.0.17_darwin_amd64.tar.gz"
      sha256 "fa03649c6bc9aa83f348562e7a6ea7996edeb2d6fc3de0ae6a0242f358b2379f"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/safegrd/cli/releases/download/v0.0.17/safegrd_0.0.17_linux_arm64.tar.gz"
      sha256 "c138616d0dc715887ebe0e14c5f87a690e02e5fa146094894be23a73134c02b7"
    end
    on_intel do
      url "https://github.com/safegrd/cli/releases/download/v0.0.17/safegrd_0.0.17_linux_amd64.tar.gz"
      sha256 "0c8121f249743a680a78876701455d07756647ffd0091fee295853e5996fea54"
    end
  end

  def install
    bin.install "safegrd"
    generate_completions_from_executable(bin/"safegrd", "completion")
  end

  def caveats
    <<~EOS
      Connect this machine to SafeGrd:
        safegrd login     # prints a URL; open it in a browser on any device
        safegrd enroll
      Or set up a standalone host that contacts no server:
        safegrd init
    EOS
  end

  test do
    assert_match "version #{version}", shell_output("#{bin}/safegrd version")
  end
end
