# Generated by scripts/homebrew-formula.sh in github.com/safegrd/cli for v0.0.42.
# Do not edit by hand: the next release overwrites it.
class Safegrd < Formula
  desc "Encrypted, immutable backups with proof that they restore"
  homepage "https://safegrd.dev"
  version "0.0.42"
  license "BUSL-1.1"

  on_macos do
    on_arm do
      url "https://github.com/safegrd/cli/releases/download/v0.0.42/safegrd_0.0.42_darwin_arm64.tar.gz"
      sha256 "83f74c482ca3f539609c793981cee5c91a3384025b2714755a5f64b732f1f8a9"
    end
    on_intel do
      url "https://github.com/safegrd/cli/releases/download/v0.0.42/safegrd_0.0.42_darwin_amd64.tar.gz"
      sha256 "64592e02864e8347f0806e3284fd92114943eebd5e41bbb5fc3ec9425ea4344c"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/safegrd/cli/releases/download/v0.0.42/safegrd_0.0.42_linux_arm64.tar.gz"
      sha256 "050174db3247327d5dd81951a66992e96218e4946ecd9f52381f7158b589356e"
    end
    on_intel do
      url "https://github.com/safegrd/cli/releases/download/v0.0.42/safegrd_0.0.42_linux_amd64.tar.gz"
      sha256 "621407ff3b8c7fa61e10cda2749f3ade72df86ab2bbaa43d64e6b73001465e09"
    end
  end

  def install
    bin.install "safegrd"
    generate_completions_from_executable(bin/"safegrd", "completion")
  end

  def caveats
    <<~EOS
      Connect this machine to SafeGrd:
        safegrd login     # prints a URL; open it in a browser on any device
        safegrd enroll
      Or set up a standalone host that contacts no server:
        safegrd init
    EOS
  end

  test do
    assert_match "version #{version}", shell_output("#{bin}/safegrd version")
  end
end
